# Generated by Django 3.2.15 on 2022-08-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_groupmember_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('message', 'member')},
        ),
    ]
